[package]
name = "atk-dpi-cli"
version = "0.1.0"
edition = "2021"
description = "Terminal utility for controlling DPI of ATK/VXE mice on Linux"
license = "GPL-3.0"
 
[[bin]]
name = "Linux-ATK"
path = "src/main.rs"
 
[dependencies]
# hidapi (см. README).
hidapi = { version = "2", default-features = false, features = ["linux-shared-hidraw"] }
 
clap = { version = "4", features = ["derive"] }
anyhow = "1"
libatk-rs = "0.1.10"
